version: "3.7"

services:
  astra:
    image: astra:v1.0.port.466
    privileged: true
    volumes:
      - ./license.txt:/etc/astra/license.txt
      - ./context/astra.conf:/etc/astra/astra.conf
    ports:
      - 466:8000
    build:
      dockerfile: Dockerfile
      context: .
